name: CI/CD Pipeline for NextJS to AWS
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
      - name: Save build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            dist
            node_modules
          
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:      
      # - uses: actions/checkout@v4
      # - name: Set up Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20.x'

      # - name: Install dependencies
      #   run: npm ci
      - name: Open build artifact for testing
        uses: actions/download-artifact@v4
      - name: Run unit Test
        run: npm test
        # run unit tests

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/master'
    steps:    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name nextjs \
            --deployment-group-name GHActions \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}